version: '3.8'

services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    volumes:
      - ./src:/app

  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - '6433:5432'


networks:
  tinkoff:

volumes:
  postgres_data:
