version: '3.8'

services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    restart: always
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - tinkoff

  db:
    image: postgres:15-alpine
    hostname: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '6433:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tinkoff

networks:
  tinkoff:

volumes:
  postgres_data: