"""create tables5

Revision ID: 67af254ef136
Revises: 8f539a8554af
Create Date: 2023-07-23 16:40:20.364042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67af254ef136'
down_revision = '8f539a8554af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancelled_payments', sa.Column('original_amount', sa.Integer(), nullable=False))
    op.add_column('cancelled_payments', sa.Column('new_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancelled_payments', 'new_amount')
    op.drop_column('cancelled_payments', 'original_amount')
    # ### end Alembic commands ###
