"""lang

Revision ID: 6db32cec3953
Revises: b38723723b35
Create Date: 2023-07-21 17:42:56.096211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6db32cec3953'
down_revision = 'b38723723b35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'pay_type',
               existing_type=postgresql.ENUM('O', 'T', name='paytype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'pay_type',
               existing_type=postgresql.ENUM('O', 'T', name='paytype'),
               nullable=False)
    # ### end Alembic commands ###
